import {
  operationDoc,
  renderPath,
  toCamel,
  toPascal,
  type GeneratedFile,
  type GeneratedSdk,
  type SdkOperation,
  type SdkSpec,
  type TypeRef,
} from "./model";

function csType(ref: TypeRef, nullable = false): string {
  const suffix = nullable ? "?" : "";
  switch (ref.kind) {
    case "primitive":
      switch (ref.name) {
        case "integer":
          return `long${suffix}`;
        case "number":
          return `double${suffix}`;
        case "boolean":
          return `bool${suffix}`;
        case "datetime":
          return `DateTimeOffset${suffix}`;
        case "any":
          return "object?";
        default:
          return `string${suffix}`;
      }
    case "array":
      return `IReadOnlyList<${csType(ref.items)}>${suffix}`;
    case "map":
      return `IReadOnlyDictionary<string, ${csType(ref.values)}>${suffix}`;
    case "model":
      return `${ref.name}${suffix}`;
    case "enum":
      return `string${suffix}`;
    case "void":
      return "object?";
  }
}

function modelsFile(spec: SdkSpec, ns: string): string {
  const records = spec.models.map((model) => {
    if (model.enumValues.length > 0 && model.properties.length === 0) {
      const members = model.enumValues
        .map(
          (value) =>
            `    [JsonStringEnumMemberName(${JSON.stringify(value)})]\n    ${toPascal(value)}`,
        )
        .join(",\n");
      return `/// <summary>${model.description ?? model.name}</summary>\npublic enum ${model.name}\n{\n${members}\n}`;
    }

    const properties = model.properties
      .map((property) => {
        const doc = `    /// <summary>${property.description ?? property.wireName}</summary>`;
        const attribute = `    [JsonPropertyName(${JSON.stringify(property.wireName)})]`;
        const type = csType(property.type, !property.required || property.nullable);
        return `${doc}\n${attribute}\n    public ${type} ${toPascal(property.name)} { get; init; }`;
      })
      .join("\n\n");

    return `/// <summary>${model.description ?? `${model.name} generated from the API specification.`}</summary>
public sealed record ${model.name}
{
${properties || "    // No properties documented."}
}`;
  });

  return `// Generated by OpenAPI Studio AI from ${spec.title} ${spec.version}.
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ${ns}.Models;

${records.join("\n\n")}
`;
}

function authApplication(spec: SdkSpec): string {
  const lines: string[] = [];
  for (const auth of spec.auth) {
    switch (auth.kind) {
      case "bearer":
      case "oauth2":
        lines.push(
          "        if (!string.IsNullOrWhiteSpace(_options.AccessToken))",
          "        {",
          '            request.Headers.TryAddWithoutValidation("Authorization", $"Bearer {_options.AccessToken}");',
          "        }",
        );
        break;
      case "basic":
        lines.push(
          "        if (!string.IsNullOrWhiteSpace(_options.Username))",
          "        {",
          '            var raw = Encoding.UTF8.GetBytes($"{_options.Username}:{_options.Password}");',
          '            request.Headers.TryAddWithoutValidation("Authorization", $"Basic {Convert.ToBase64String(raw)}");',
          "        }",
        );
        break;
      case "apiKeyHeader":
        lines.push(
          "        if (!string.IsNullOrWhiteSpace(_options.ApiKey))",
          "        {",
          `            request.Headers.TryAddWithoutValidation(${JSON.stringify(auth.parameterName ?? "X-API-Key")}, _options.ApiKey);`,
          "        }",
        );
        break;
      default:
        break;
    }
  }
  return lines.join("\n") || "        // This API declares no security schemes.";
}

function methodFor(operation: SdkOperation): string {
  const args = [
    ...operation.pathParams.map(
      (parameter) => `${csType(parameter.type)} ${toCamel(parameter.name)}`,
    ),
    ...(operation.requestBody ? ["object? body = null"] : []),
    ...operation.queryParams.map(
      (parameter) => `${csType(parameter.type, true)} ${toCamel(parameter.name)} = null`,
    ),
    "CancellationToken cancellationToken = default",
  ];

  const path = renderPath(
    operation,
    (parameter) => `{Uri.EscapeDataString(${toCamel(parameter.name)}.ToString()!)}`,
  );
  const querySetters = operation.queryParams
    .map(
      (parameter) =>
        `        if (${toCamel(parameter.name)} is not null) query[${JSON.stringify(parameter.wireName)}] = ${toCamel(parameter.name)}.ToString()!;`,
    )
    .join("\n");

  const doc = [
    "    /// <summary>",
    ...operationDoc(operation).map((line) => `    /// ${line}`),
    "    /// </summary>",
  ].join("\n");

  return `${doc}
    public Task<JsonElement?> ${toPascal(operation.methodName)}Async(${args.join(", ")})
    {
        var query = new Dictionary<string, string>();
${querySetters}
        return SendAsync(HttpMethod.${toPascal(operation.httpMethod.toLowerCase())}, $"${path}", query, ${operation.requestBody ? "body" : "null"}, cancellationToken);
    }`;
}

function clientFile(spec: SdkSpec, ns: string): string {
  const authProperties = new Set<string>();
  for (const auth of spec.auth) {
    if (auth.kind === "bearer" || auth.kind === "oauth2") {
      authProperties.add(
        "    /// <summary>Bearer token sent on every request.</summary>\n    public string? AccessToken { get; init; }",
      );
    }
    if (auth.kind === "basic") {
      authProperties.add(
        "    public string? Username { get; init; }\n\n    public string? Password { get; init; }",
      );
    }
    if (auth.kind === "apiKeyHeader" || auth.kind === "apiKeyQuery") {
      authProperties.add(
        "    /// <summary>API key credential.</summary>\n    public string? ApiKey { get; init; }",
      );
    }
  }

  return `// Generated by OpenAPI Studio AI from ${spec.title} ${spec.version}.
#nullable enable

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace ${ns};

/// <summary>Thrown for any non-2xx response.</summary>
public sealed class ApiException : Exception
{
    public ApiException(int statusCode, string body, string? requestId)
        : base($"HTTP {statusCode}")
    {
        StatusCode = statusCode;
        Body = body;
        RequestId = requestId;
    }

    public int StatusCode { get; }

    public string Body { get; }

    public string? RequestId { get; }

    /// <summary>True when retrying the request could succeed.</summary>
    public bool IsRetryable => StatusCode == 429 || StatusCode >= 500;
}

/// <summary>Configuration for <see cref="${spec.namespace}Client"/>.</summary>
public sealed record ${spec.namespace}Options
{
    public string BaseUrl { get; init; } = ${JSON.stringify(spec.baseUrl)};

    public TimeSpan Timeout { get; init; } = TimeSpan.FromSeconds(30);

    public int MaxRetries { get; init; } = 2;

${[...authProperties].join("\n\n")}
}

/// <summary>${spec.description}</summary>
public sealed class ${spec.namespace}Client : IDisposable
{
    private readonly ${spec.namespace}Options _options;
    private readonly HttpClient _httpClient;
    private readonly bool _ownsClient;

    public ${spec.namespace}Client(${spec.namespace}Options? options = null, HttpClient? httpClient = null)
    {
        _options = options ?? new ${spec.namespace}Options();
        _ownsClient = httpClient is null;
        _httpClient = httpClient ?? new HttpClient();
        _httpClient.Timeout = _options.Timeout;
    }

    private void Authenticate(HttpRequestMessage request)
    {
${authApplication(spec)}
    }

    private async Task<JsonElement?> SendAsync(
        HttpMethod method,
        string path,
        IReadOnlyDictionary<string, string> query,
        object? body,
        CancellationToken cancellationToken)
    {
        var queryString = query.Count == 0
            ? string.Empty
            : "?" + string.Join("&", BuildQuery(query));
        var url = $"{_options.BaseUrl.TrimEnd('/')}{path}{queryString}";

        Exception? lastError = null;
        for (var attempt = 0; attempt <= _options.MaxRetries; attempt++)
        {
            using var request = new HttpRequestMessage(method, url);
            request.Headers.TryAddWithoutValidation("Accept", "application/json");
            if (body is not null)
            {
                request.Content = JsonContent.Create(body);
            }
            Authenticate(request);

            try
            {
                using var response = await _httpClient.SendAsync(request, cancellationToken).ConfigureAwait(false);
                var payload = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                if (!response.IsSuccessStatusCode)
                {
                    response.Headers.TryGetValues("x-request-id", out var requestIds);
                    var error = new ApiException((int)response.StatusCode, payload, FirstOrNull(requestIds));
                    if (error.IsRetryable && attempt < _options.MaxRetries)
                    {
                        lastError = error;
                        await Task.Delay(TimeSpan.FromMilliseconds(Math.Pow(2, attempt) * 250), cancellationToken)
                            .ConfigureAwait(false);
                        continue;
                    }
                    throw error;
                }

                if (string.IsNullOrEmpty(payload))
                {
                    return null;
                }
                return JsonDocument.Parse(payload).RootElement.Clone();
            }
            catch (HttpRequestException exception)
            {
                lastError = exception;
                if (attempt == _options.MaxRetries)
                {
                    break;
                }
                await Task.Delay(TimeSpan.FromMilliseconds(Math.Pow(2, attempt) * 250), cancellationToken)
                    .ConfigureAwait(false);
            }
        }

        throw lastError ?? new HttpRequestException("Request failed");
    }

    private static IEnumerable<string> BuildQuery(IReadOnlyDictionary<string, string> query)
    {
        foreach (var pair in query)
        {
            yield return $"{Uri.EscapeDataString(pair.Key)}={Uri.EscapeDataString(pair.Value)}";
        }
    }

    private static string? FirstOrNull(IEnumerable<string>? values)
    {
        if (values is null)
        {
            return null;
        }
        foreach (var value in values)
        {
            return value;
        }
        return null;
    }

    public void Dispose()
    {
        if (_ownsClient)
        {
            _httpClient.Dispose();
        }
    }

${spec.operations.map((operation) => methodFor(operation)).join("\n\n")}
}
`;
}

export function generateCSharp(spec: SdkSpec): GeneratedSdk {
  const ns = spec.namespace.replace(/[^A-Za-z0-9]/g, "") || "ApiClient";
  const first = spec.operations[0];

  const files: GeneratedFile[] = [
    { path: `src/${ns}Client.cs`, contents: clientFile(spec, ns) },
    { path: `src/Models.cs`, contents: modelsFile(spec, ns) },
    {
      path: `src/${ns}.csproj`,
      contents: `<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>${ns}</PackageId>
    <Version>${spec.version}</Version>
    <Description>${spec.description}</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
`,
    },
    {
      path: "README.md",
      contents: `# ${spec.title} — C# SDK

${spec.description}

Generated by OpenAPI Studio AI from \`${spec.title}\` v${spec.version}. Targets .NET 8.

\`\`\`bash
dotnet add package ${ns}
\`\`\`

\`\`\`csharp
using ${ns};

using var client = new ${ns}Client(new ${ns}Options { BaseUrl = "${spec.baseUrl}" });

try
{
    var result = await client.${first ? toPascal(first.methodName) : "Call"}Async(${first?.pathParams.map(() => '"123"').join(", ") ?? ""});
    Console.WriteLine(result);
}
catch (ApiException error)
{
    Console.Error.WriteLine($"{error.StatusCode}: {error.Body}");
}
\`\`\`
`,
    },
  ];

  return {
    language: "csharp",
    files,
    entryPoint: `src/${ns}Client.cs`,
    installCommand: `dotnet add package ${ns}`,
  };
}
