import {
  operationDoc,
  renderPath,
  toPascal,
  toCamel,
  type GeneratedFile,
  type GeneratedSdk,
  type SdkOperation,
  type SdkSpec,
  type TypeRef,
} from "./model";

function goType(ref: TypeRef, pointer = false): string {
  switch (ref.kind) {
    case "primitive":
      switch (ref.name) {
        case "integer":
          return pointer ? "*int64" : "int64";
        case "number":
          return pointer ? "*float64" : "float64";
        case "boolean":
          return pointer ? "*bool" : "bool";
        case "datetime":
          return pointer ? "*time.Time" : "time.Time";
        case "any":
          return "any";
        default:
          return pointer ? "*string" : "string";
      }
    case "array":
      return `[]${goType(ref.items)}`;
    case "map":
      return `map[string]${goType(ref.values)}`;
    case "model":
      return `*${ref.name}`;
    case "enum":
      return pointer ? "*string" : "string";
    case "void":
      return "any";
  }
}

function modelsFile(spec: SdkSpec, pkg: string): string {
  const usesTime = spec.models.some((model) =>
    model.properties.some((property) => goType(property.type).includes("time.Time")),
  );

  const structs = spec.models.map((model) => {
    if (model.enumValues.length > 0 && model.properties.length === 0) {
      const consts = model.enumValues
        .map(
          (value) => `\t${model.name}${toPascal(value)} ${model.name} = ${JSON.stringify(value)}`,
        )
        .join("\n");
      return `// ${model.name} ${model.description ?? "enumeration."}\ntype ${model.name} string\n\nconst (\n${consts}\n)`;
    }

    const fields = model.properties
      .map((property) => {
        const omit = property.required ? "" : ",omitempty";
        const doc = property.description ? `\t// ${property.description.split("\n")[0]}\n` : "";
        return `${doc}\t${toPascal(property.name)} ${goType(property.type, !property.required)} \`json:"${property.wireName}${omit}"\``;
      })
      .join("\n");
    return `// ${model.name} ${model.description ?? "generated model."}\ntype ${model.name} struct {\n${fields}\n}`;
  });

  return `// Code generated by OpenAPI Studio AI from ${spec.title} ${spec.version}. DO NOT EDIT.

package ${pkg}
${usesTime ? '\nimport "time"\n' : ""}
${structs.join("\n\n")}
`;
}

function authApplication(spec: SdkSpec): string {
  const lines: string[] = [];
  for (const auth of spec.auth) {
    switch (auth.kind) {
      case "bearer":
      case "oauth2":
        lines.push(
          '\tif c.AccessToken != "" {',
          '\t\treq.Header.Set("Authorization", "Bearer "+c.AccessToken)',
          "\t}",
        );
        break;
      case "basic":
        lines.push(
          '\tif c.Username != "" {',
          "\t\treq.SetBasicAuth(c.Username, c.Password)",
          "\t}",
        );
        break;
      case "apiKeyHeader":
        lines.push(
          '\tif c.APIKey != "" {',
          `\t\treq.Header.Set(${JSON.stringify(auth.parameterName ?? "X-API-Key")}, c.APIKey)`,
          "\t}",
        );
        break;
      case "apiKeyQuery":
        lines.push(
          '\tif c.APIKey != "" {',
          "\t\tq := req.URL.Query()",
          `\t\tq.Set(${JSON.stringify(auth.parameterName ?? "api_key")}, c.APIKey)`,
          "\t\treq.URL.RawQuery = q.Encode()",
          "\t}",
        );
        break;
      default:
        break;
    }
  }
  return lines.join("\n") || "\t// This API declares no security schemes.";
}

function authFields(spec: SdkSpec): string {
  const fields = new Set<string>();
  for (const auth of spec.auth) {
    if (auth.kind === "bearer" || auth.kind === "oauth2")
      fields.add("\t// AccessToken is sent as a bearer token.\n\tAccessToken string");
    if (auth.kind === "basic") fields.add("\tUsername string\n\tPassword string");
    if (auth.kind === "apiKeyHeader" || auth.kind === "apiKeyQuery")
      fields.add("\t// APIKey is the API key credential.\n\tAPIKey string");
  }
  return [...fields].join("\n");
}

function methodFor(operation: SdkOperation): string {
  const name = toPascal(operation.methodName);
  const args = [
    "ctx context.Context",
    ...operation.pathParams.map(
      (parameter) => `${toCamel(parameter.name)} ${goType(parameter.type)}`,
    ),
    ...(operation.requestBody ? ["body any"] : []),
    ...(operation.queryParams.length > 0 ? [`opts *${name}Options`] : []),
  ];

  const optionsStruct =
    operation.queryParams.length > 0
      ? `// ${name}Options carries the optional query parameters of ${name}.
type ${name}Options struct {
${operation.queryParams
  .map(
    (parameter) =>
      `\t${toPascal(parameter.name)} ${goType(parameter.type, true)} \`url:"${parameter.wireName}"\``,
  )
  .join("\n")}
}

`
      : "";

  const querySetters =
    operation.queryParams.length > 0
      ? `\tif opts != nil {\n${operation.queryParams
          .map(
            (parameter) =>
              `\t\tif opts.${toPascal(parameter.name)} != nil {\n\t\t\tquery.Set(${JSON.stringify(parameter.wireName)}, fmt.Sprintf("%v", *opts.${toPascal(parameter.name)}))\n\t\t}`,
          )
          .join("\n")}\n\t}`
      : "";

  const path = renderPath(operation, () => "%v");
  const pathArgs = operation.pathParams.map(
    (parameter) => `url.PathEscape(fmt.Sprintf("%v", ${toCamel(parameter.name)}))`,
  );
  const pathExpr =
    pathArgs.length > 0
      ? `fmt.Sprintf(${JSON.stringify(path)}, ${pathArgs.join(", ")})`
      : JSON.stringify(path);

  const doc = operationDoc(operation)
    .map((line) => `// ${line}`)
    .join("\n");

  return `${optionsStruct}${doc.replace(/^\/\/ /, `// ${name} `)}
func (c *Client) ${name}(${args.join(", ")}) (any, error) {
	query := url.Values{}
${querySetters}
	return c.do(ctx, ${JSON.stringify(operation.httpMethod)}, ${pathExpr}, query, ${operation.requestBody ? "body" : "nil"})
}`;
}

function clientFile(spec: SdkSpec, pkg: string): string {
  return `// Code generated by OpenAPI Studio AI from ${spec.title} ${spec.version}. DO NOT EDIT.

// Package ${pkg} is a client for ${spec.title}.
//
// ${spec.description}
package ${pkg}

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// DefaultBaseURL is the server declared by the specification.
const DefaultBaseURL = ${JSON.stringify(spec.baseUrl)}

// APIError is returned for any non-2xx response.
type APIError struct {
	StatusCode int
	Body       string
	RequestID  string
}

func (e *APIError) Error() string {
	return fmt.Sprintf("%s: %d %s", ${JSON.stringify(spec.title)}, e.StatusCode, e.Body)
}

// Retryable reports whether retrying the request could succeed.
func (e *APIError) Retryable() bool {
	return e.StatusCode == http.StatusTooManyRequests || e.StatusCode >= 500
}

// Client talks to ${spec.title}.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
	MaxRetries int
${authFields(spec)}
}

// Option configures a Client.
type Option func(*Client)

// WithBaseURL overrides the API origin.
func WithBaseURL(baseURL string) Option {
	return func(c *Client) { c.BaseURL = strings.TrimRight(baseURL, "/") }
}

// WithHTTPClient injects a custom transport.
func WithHTTPClient(httpClient *http.Client) Option {
	return func(c *Client) { c.HTTPClient = httpClient }
}

// New creates a Client with sensible defaults.
func New(opts ...Option) *Client {
	c := &Client{
		BaseURL:    DefaultBaseURL,
		HTTPClient: &http.Client{Timeout: 30 * time.Second},
		MaxRetries: 2,
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func (c *Client) authenticate(req *http.Request) {
${authApplication(spec)}
}

func (c *Client) do(ctx context.Context, method, path string, query url.Values, body any) (any, error) {
	var lastErr error

	for attempt := 0; attempt <= c.MaxRetries; attempt++ {
		var reader io.Reader
		if body != nil {
			encoded, err := json.Marshal(body)
			if err != nil {
				return nil, fmt.Errorf("encode request body: %w", err)
			}
			reader = bytes.NewReader(encoded)
		}

		endpoint := c.BaseURL + path
		if encodedQuery := query.Encode(); encodedQuery != "" {
			endpoint += "?" + encodedQuery
		}

		req, err := http.NewRequestWithContext(ctx, method, endpoint, reader)
		if err != nil {
			return nil, fmt.Errorf("build request: %w", err)
		}
		req.Header.Set("Accept", "application/json")
		if body != nil {
			req.Header.Set("Content-Type", "application/json")
		}
		c.authenticate(req)

		resp, err := c.HTTPClient.Do(req)
		if err != nil {
			lastErr = err
			if attempt == c.MaxRetries {
				break
			}
			time.Sleep(backoff(attempt))
			continue
		}

		payload, readErr := io.ReadAll(resp.Body)
		resp.Body.Close()
		if readErr != nil {
			return nil, fmt.Errorf("read response: %w", readErr)
		}

		if resp.StatusCode >= 400 {
			apiErr := &APIError{
				StatusCode: resp.StatusCode,
				Body:       string(payload),
				RequestID:  resp.Header.Get("X-Request-Id"),
			}
			if apiErr.Retryable() && attempt < c.MaxRetries {
				lastErr = apiErr
				time.Sleep(backoff(attempt))
				continue
			}
			return nil, apiErr
		}

		if resp.StatusCode == http.StatusNoContent || len(payload) == 0 {
			return nil, nil
		}

		var decoded any
		if err := json.Unmarshal(payload, &decoded); err != nil {
			return string(payload), nil
		}
		return decoded, nil
	}

	return nil, lastErr
}

func backoff(attempt int) time.Duration {
	return time.Duration(math.Pow(2, float64(attempt))*250) * time.Millisecond
}

${spec.operations.map((operation) => methodFor(operation)).join("\n\n")}
`;
}

export function generateGo(spec: SdkSpec): GeneratedSdk {
  const pkg = spec.packageName.replace(/[^a-z0-9]/gi, "").toLowerCase() || "apiclient";
  const first = spec.operations[0];

  const files: GeneratedFile[] = [
    { path: `${pkg}/client.go`, contents: clientFile(spec, pkg) },
    { path: `${pkg}/models.go`, contents: modelsFile(spec, pkg) },
    {
      path: "go.mod",
      contents: `module github.com/your-org/${spec.packageName}\n\ngo 1.22\n`,
    },
    {
      path: "README.md",
      contents: `# ${spec.title} — Go SDK

${spec.description}

Generated by OpenAPI Studio AI from \`${spec.title}\` v${spec.version}.

\`\`\`bash
go get github.com/your-org/${spec.packageName}
\`\`\`

\`\`\`go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/your-org/${spec.packageName}/${pkg}"
)

func main() {
	client := ${pkg}.New(${pkg}.WithBaseURL("${spec.baseUrl}"))

	result, err := client.${first ? toPascal(first.methodName) : "Call"}(context.Background()${first?.pathParams.map(() => ', "123"').join("") ?? ""}${first?.requestBody ? ", nil" : ""}${(first?.queryParams.length ?? 0) > 0 ? ", nil" : ""})
	if err != nil {
		var apiErr *${pkg}.APIError
		if errors.As(err, &apiErr) {
			log.Fatalf("api error %d: %s", apiErr.StatusCode, apiErr.Body)
		}
		log.Fatal(err)
	}
	fmt.Println(result)
}
\`\`\`

Requests to 429 and 5xx are retried with exponential backoff (\`MaxRetries\`, default 2).
`,
    },
  ];

  return {
    language: "go",
    files,
    entryPoint: `${pkg}/client.go`,
    installCommand: `go get github.com/your-org/${spec.packageName}`,
  };
}
