import {
  operationDoc,
  renderPath,
  type GeneratedFile,
  type GeneratedSdk,
  type SdkOperation,
  type SdkSpec,
  type TypeRef,
} from "./model";

function jsDocType(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      if (ref.name === "integer" || ref.name === "number") return "number";
      if (ref.name === "boolean") return "boolean";
      if (ref.name === "any") return "*";
      return "string";
    case "array":
      return `Array<${jsDocType(ref.items)}>`;
    case "map":
      return `Object.<string, ${jsDocType(ref.values)}>`;
    case "model":
      return ref.name;
    case "enum":
      return "string";
    case "void":
      return "void";
  }
}

function typedefs(spec: SdkSpec): string {
  const blocks = spec.models.map((model) => {
    const lines = [
      "/**",
      ...(model.description ? [` * ${model.description}`, " *"] : []),
      ` * @typedef {Object} ${model.name}`,
      ...model.properties.map((property) => {
        const type = property.nullable ? `?${jsDocType(property.type)}` : jsDocType(property.type);
        const name = property.required ? property.name : `[${property.name}]`;
        return ` * @property {${type}} ${name}${property.description ? ` ${property.description}` : ""}`;
      }),
      " */",
    ];
    return lines.join("\n");
  });
  return `// Generated by OpenAPI Studio AI from ${spec.title} ${spec.version}.\n\n${blocks.join("\n\n")}\n\nexport {};\n`;
}

function authApplication(spec: SdkSpec): string {
  const lines: string[] = [];
  for (const auth of spec.auth) {
    switch (auth.kind) {
      case "bearer":
      case "oauth2":
        lines.push(
          "    if (this.options.accessToken) {",
          "      const token =",
          '        typeof this.options.accessToken === "function"',
          "          ? await this.options.accessToken()",
          "          : this.options.accessToken;",
          '      if (token) headers.set("authorization", `Bearer ${token}`);',
          "    }",
        );
        break;
      case "basic":
        lines.push(
          "    if (this.options.username !== undefined) {",
          '      const raw = `${this.options.username}:${this.options.password ?? ""}`;',
          "      const encoded =",
          '        typeof btoa === "function" ? btoa(raw) : Buffer.from(raw, "utf8").toString("base64");',
          '      headers.set("authorization", `Basic ${encoded}`);',
          "    }",
        );
        break;
      case "apiKeyHeader":
        lines.push(
          `    if (this.options.apiKey) headers.set(${JSON.stringify((auth.parameterName ?? "x-api-key").toLowerCase())}, this.options.apiKey);`,
        );
        break;
      case "apiKeyQuery":
        lines.push(
          `    if (this.options.apiKey) query.set(${JSON.stringify(auth.parameterName ?? "api_key")}, this.options.apiKey);`,
        );
        break;
      default:
        break;
    }
  }
  return lines.join("\n") || "    // This API declares no security schemes.";
}

function methodFor(operation: SdkOperation): string {
  const params = [
    ...operation.pathParams.map((parameter) => parameter.name),
    ...(operation.requestBody ? ["body"] : []),
    "options = {}",
  ];

  const doc = [
    "  /**",
    ...operationDoc(operation).map((line) => `   * ${line}`),
    ...operation.pathParams.map(
      (parameter) =>
        `   * @param {${jsDocType(parameter.type)}} ${parameter.name}${parameter.description ? ` ${parameter.description}` : ""}`,
    ),
    ...(operation.requestBody
      ? [`   * @param {${jsDocType(operation.requestBody.type)}} body`]
      : []),
    "   * @param {Object} [options]",
    ...operation.queryParams.map(
      (parameter) =>
        `   * @param {${jsDocType(parameter.type)}} [options.${parameter.name}]${parameter.description ? ` ${parameter.description}` : ""}`,
    ),
    `   * @returns {Promise<${jsDocType(operation.responseType)}>}`,
    "   */",
  ].join("\n");

  const path = renderPath(
    operation,
    (parameter) => `\${encodeURIComponent(String(${parameter.name}))}`,
  );
  const querySetters = operation.queryParams
    .map(
      (parameter) =>
        `    if (options.${parameter.name} !== undefined) query.set(${JSON.stringify(parameter.wireName)}, String(options.${parameter.name}));`,
    )
    .join("\n");
  const headerSetters = operation.headerParams
    .map(
      (parameter) =>
        `    if (options[${JSON.stringify(parameter.wireName)}] !== undefined) headers[${JSON.stringify(parameter.wireName.toLowerCase())}] = String(options[${JSON.stringify(parameter.wireName)}]);`,
    )
    .join("\n");

  return [
    doc,
    `  async ${operation.methodName}(${params.join(", ")}) {`,
    "    const query = new URLSearchParams();",
    querySetters,
    "    const headers = {};",
    headerSetters,
    "    return this.request({",
    `      method: ${JSON.stringify(operation.httpMethod)},`,
    `      path: \`${path}\`,`,
    "      query,",
    "      headers,",
    operation.requestBody ? "      body," : "      body: undefined,",
    "      signal: options.signal,",
    "    });",
    "  }",
  ]
    .filter((line) => line !== "")
    .join("\n");
}

function clientFile(spec: SdkSpec): string {
  return `// Generated by OpenAPI Studio AI from ${spec.title} ${spec.version}.

/** Thrown for any non-2xx response. */
export class ApiError extends Error {
  /**
   * @param {number} status
   * @param {string} statusText
   * @param {*} body
   * @param {?string} requestId
   */
  constructor(status, statusText, body, requestId) {
    super(\`\${status} \${statusText}\`);
    this.name = "ApiError";
    this.status = status;
    this.statusText = statusText;
    this.body = body;
    this.requestId = requestId;
  }

  /** @returns {boolean} True when retrying the request could succeed. */
  get retryable() {
    return this.status === 429 || this.status >= 500;
  }
}

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * ${spec.description}
 */
export class ${spec.namespace}Client {
  /**
   * @param {Object} [options]
   * @param {string} [options.baseUrl]
   * @param {typeof fetch} [options.fetch]
   * @param {Object.<string,string>} [options.headers]
   * @param {number} [options.timeoutMs]
   * @param {number} [options.maxRetries]
   */
  constructor(options = {}) {
    this.options = options;
    this.baseUrl = (options.baseUrl ?? ${JSON.stringify(spec.baseUrl)}).replace(/\\/$/, "");
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    if (!this.fetchImpl) {
      throw new Error("No fetch implementation available. Pass one via options.fetch.");
    }
  }

  async applyAuth(headers, query) {
${authApplication(spec)}
  }

  async request(init) {
    const headers = new Headers({ accept: "application/json", ...this.options.headers, ...init.headers });
    const query = new URLSearchParams(init.query);
    await this.applyAuth(headers, query);

    if (init.body !== undefined && !headers.has("content-type")) {
      headers.set("content-type", "application/json");
    }

    const search = query.toString();
    const url = \`\${this.baseUrl}\${init.path}\${search ? \`?\${search}\` : ""}\`;
    const maxRetries = this.options.maxRetries ?? 2;
    let lastError;

    for (let attempt = 0; attempt <= maxRetries; attempt += 1) {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), this.options.timeoutMs ?? 30000);
      if (init.signal) init.signal.addEventListener("abort", () => controller.abort(), { once: true });

      try {
        const response = await this.fetchImpl(url, {
          method: init.method,
          headers,
          body: init.body === undefined ? undefined : JSON.stringify(init.body),
          signal: controller.signal,
        });

        if (!response.ok) {
          const payload = await this.readBody(response);
          const error = new ApiError(
            response.status,
            response.statusText,
            payload,
            response.headers.get("x-request-id"),
          );
          if (error.retryable && attempt < maxRetries) {
            const retryAfter = Number(response.headers.get("retry-after"));
            await sleep(Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : 2 ** attempt * 250);
            lastError = error;
            continue;
          }
          throw error;
        }

        if (response.status === 204) return undefined;
        return await this.readBody(response);
      } catch (error) {
        if (error instanceof ApiError) throw error;
        lastError = error;
        if (attempt >= maxRetries) break;
        await sleep(2 ** attempt * 250);
      } finally {
        clearTimeout(timeout);
      }
    }
    throw lastError instanceof Error ? lastError : new Error("Request failed");
  }

  async readBody(response) {
    const contentType = response.headers.get("content-type") ?? "";
    if (contentType.includes("json")) {
      try {
        return await response.json();
      } catch {
        return null;
      }
    }
    return await response.text();
  }

  /**
   * Iterate every page of a paginated operation.
   * @template T
   * @param {(cursor: (number|string|undefined)) => Promise<T>} fetchPage
   * @param {(page: T) => (number|string|undefined)} [nextCursor]
   * @param {number} [maxPages]
   */
  async *paginate(fetchPage, nextCursor = defaultNextCursor, maxPages = 100) {
    let cursor;
    for (let index = 0; index < maxPages; index += 1) {
      const page = await fetchPage(cursor);
      yield page;
      const next = nextCursor(page);
      if (next === undefined || next === null || next === cursor) return;
      cursor = next;
    }
  }

${spec.operations.map((operation) => methodFor(operation)).join("\n\n")}
}

export function defaultNextCursor(page) {
  if (page && typeof page === "object") {
    const candidate = page.nextCursor ?? page.next_cursor ?? page.next ?? page.cursor;
    if (typeof candidate === "string" || typeof candidate === "number") return candidate;
  }
  return undefined;
}

export default ${spec.namespace}Client;
`;
}

export function generateJavaScript(spec: SdkSpec): GeneratedSdk {
  const first = spec.operations[0];
  const call = first
    ? `await client.${first.methodName}(${[
        ...first.pathParams.map(() => '"123"'),
        ...(first.requestBody ? ["{ /* body */ }"] : []),
      ].join(", ")});`
    : "// No operations documented yet.";

  const files: GeneratedFile[] = [
    { path: "src/models.js", contents: typedefs(spec) },
    { path: "src/client.js", contents: clientFile(spec) },
    { path: "src/index.js", contents: `export * from "./client.js";\n` },
    {
      path: "package.json",
      contents: `${JSON.stringify(
        {
          name: spec.packageName,
          version: spec.version,
          description: spec.description,
          type: "module",
          main: "src/index.js",
          files: ["src"],
          license: "MIT",
        },
        null,
        2,
      )}\n`,
    },
    {
      path: "README.md",
      contents: `# ${spec.title} — JavaScript SDK

${spec.description}

Generated by OpenAPI Studio AI from \`${spec.title}\` v${spec.version}.

\`\`\`bash
npm install ${spec.packageName}
\`\`\`

\`\`\`js
import { ${spec.namespace}Client, ApiError } from "${spec.packageName}";

const client = new ${spec.namespace}Client({ baseUrl: "${spec.baseUrl}" });

try {
  ${call}
} catch (error) {
  if (error instanceof ApiError) console.error(error.status, error.body);
}
\`\`\`
`,
    },
  ];

  return {
    language: "javascript",
    files,
    entryPoint: "src/client.js",
    installCommand: `npm install ${spec.packageName}`,
  };
}
