import {
  operationDoc,
  renderPath,
  toCamel,
  toPascal,
  type GeneratedFile,
  type GeneratedSdk,
  type SdkOperation,
  type SdkSpec,
  type TypeRef,
} from "./model";

function phpType(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      switch (ref.name) {
        case "integer":
          return "int";
        case "number":
          return "float";
        case "boolean":
          return "bool";
        case "any":
          return "mixed";
        default:
          return "string";
      }
    case "array":
      return "array";
    case "map":
      return "array";
    case "model":
      return ref.name;
    case "enum":
      return "string";
    case "void":
      return "void";
  }
}

function docType(ref: TypeRef): string {
  switch (ref.kind) {
    case "array":
      return `${docType(ref.items)}[]`;
    case "map":
      return `array<string, ${docType(ref.values)}>`;
    default:
      return phpType(ref);
  }
}

function modelFiles(spec: SdkSpec, ns: string): GeneratedFile[] {
  return spec.models
    .filter((model) => model.properties.length > 0)
    .map((model) => {
      const properties = model.properties
        .map((property) => {
          const type =
            property.required && !property.nullable
              ? phpType(property.type)
              : `?${phpType(property.type)}`;
          return `    /** @var ${docType(property.type)}${property.required ? "" : "|null"} ${property.description ?? ""} */\n    public ${type === "?mixed" ? "mixed" : type} $${toCamel(property.name)};`;
        })
        .join("\n\n");

      const hydrate = model.properties
        .map(
          (property) =>
            `        $model->${toCamel(property.name)} = $payload[${JSON.stringify(property.wireName)}] ?? null;`,
        )
        .join("\n");

      const serialise = model.properties
        .map(
          (property) =>
            `            ${JSON.stringify(property.wireName)} => $this->${toCamel(property.name)},`,
        )
        .join("\n");

      return {
        path: `src/Model/${model.name}.php`,
        contents: `<?php

declare(strict_types=1);

namespace ${ns}\\Model;

/**
 * ${model.description ?? `${model.name} generated from the API specification.`}
 *
 * Generated by OpenAPI Studio AI — do not edit by hand.
 */
final class ${model.name}
{
${properties}

    /**
     * @param array<string, mixed> $payload
     */
    public static function fromArray(array $payload): self
    {
        $model = new self();
${hydrate}

        return $model;
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
${serialise}
        ];
    }
}
`,
      };
    });
}

function authApplication(spec: SdkSpec): string {
  const lines: string[] = [];
  for (const auth of spec.auth) {
    switch (auth.kind) {
      case "bearer":
      case "oauth2":
        lines.push(
          "        if ($this->accessToken !== null) {",
          "            $headers[] = 'Authorization: Bearer ' . $this->accessToken;",
          "        }",
        );
        break;
      case "basic":
        lines.push(
          "        if ($this->username !== null) {",
          "            $headers[] = 'Authorization: Basic ' . base64_encode($this->username . ':' . ($this->password ?? ''));",
          "        }",
        );
        break;
      case "apiKeyHeader":
        lines.push(
          "        if ($this->apiKey !== null) {",
          `            $headers[] = ${JSON.stringify(auth.parameterName ?? "X-API-Key")} . ': ' . $this->apiKey;`,
          "        }",
        );
        break;
      case "apiKeyQuery":
        lines.push(
          "        if ($this->apiKey !== null) {",
          `            $query[${JSON.stringify(auth.parameterName ?? "api_key")}] = $this->apiKey;`,
          "        }",
        );
        break;
      default:
        break;
    }
  }
  return lines.join("\n") || "        // This API declares no security schemes.";
}

function constructorParams(spec: SdkSpec): string {
  const params = [`        private string $baseUrl = ${JSON.stringify(spec.baseUrl)},`];
  const seen = new Set<string>();
  for (const auth of spec.auth) {
    if ((auth.kind === "bearer" || auth.kind === "oauth2") && !seen.has("accessToken")) {
      seen.add("accessToken");
      params.push("        private ?string $accessToken = null,");
    }
    if (auth.kind === "basic" && !seen.has("username")) {
      seen.add("username");
      params.push(
        "        private ?string $username = null,",
        "        private ?string $password = null,",
      );
    }
    if ((auth.kind === "apiKeyHeader" || auth.kind === "apiKeyQuery") && !seen.has("apiKey")) {
      seen.add("apiKey");
      params.push("        private ?string $apiKey = null,");
    }
  }
  params.push("        private int $timeoutSeconds = 30,", "        private int $maxRetries = 2,");
  return params.join("\n");
}

function methodFor(operation: SdkOperation): string {
  const args = [
    ...operation.pathParams.map(
      (parameter) => `${phpType(parameter.type)} $${toCamel(parameter.name)}`,
    ),
    ...(operation.requestBody ? ["?array $body = null"] : []),
    ...operation.queryParams.map(
      (parameter) => `?${phpType(parameter.type)} $${toCamel(parameter.name)} = null`,
    ),
  ];

  const path = renderPath(
    operation,
    (parameter) => `' . rawurlencode((string) $${toCamel(parameter.name)}) . '`,
  );
  const querySetters = operation.queryParams
    .map(
      (parameter) =>
        `        if ($${toCamel(parameter.name)} !== null) {\n            $query[${JSON.stringify(parameter.wireName)}] = $${toCamel(parameter.name)};\n        }`,
    )
    .join("\n");

  const doc = [
    "    /**",
    ...operationDoc(operation).map((line) => `     * ${line}`),
    "     *",
    "     * @return mixed",
    "     * @throws ApiException",
    "     */",
  ].join("\n");

  return `${doc}
    public function ${toCamel(operation.methodName)}(${args.join(", ")}): mixed
    {
        $query = [];
${querySetters}

        return $this->request(${JSON.stringify(operation.httpMethod)}, '${path}', $query, ${operation.requestBody ? "$body" : "null"});
    }`;
}

function clientFile(spec: SdkSpec, ns: string): string {
  return `<?php

declare(strict_types=1);

namespace ${ns};

/**
 * ${spec.description}
 *
 * Generated by OpenAPI Studio AI from ${spec.title} ${spec.version} — do not edit by hand.
 */
final class ${spec.namespace}Client
{
    public function __construct(
${constructorParams(spec)}
    ) {
        $this->baseUrl = rtrim($this->baseUrl, '/');
    }

    /**
     * @param array<string, mixed> $query
     * @param array<string, mixed>|null $body
     * @throws ApiException
     */
    private function request(string $method, string $path, array $query = [], ?array $body = null): mixed
    {
        $headers = ['Accept: application/json'];
${authApplication(spec)}

        if ($body !== null) {
            $headers[] = 'Content-Type: application/json';
        }

        $url = $this->baseUrl . $path;
        if ($query !== []) {
            $url .= '?' . http_build_query($query);
        }

        $lastError = null;
        for ($attempt = 0; $attempt <= $this->maxRetries; $attempt++) {
            $handle = curl_init($url);
            if ($handle === false) {
                throw new ApiException(0, 'Unable to initialise cURL', null);
            }

            curl_setopt_array($handle, [
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_CUSTOMREQUEST => $method,
                CURLOPT_HTTPHEADER => $headers,
                CURLOPT_TIMEOUT => $this->timeoutSeconds,
                CURLOPT_POSTFIELDS => $body === null ? null : json_encode($body, JSON_THROW_ON_ERROR),
            ]);

            $raw = curl_exec($handle);
            $status = (int) curl_getinfo($handle, CURLINFO_RESPONSE_CODE);
            $curlError = curl_error($handle);
            curl_close($handle);

            if ($raw === false) {
                $lastError = new ApiException(0, $curlError, null);
                if ($attempt === $this->maxRetries) {
                    break;
                }
                usleep((int) (2 ** $attempt * 250_000));
                continue;
            }

            if ($status >= 400) {
                $error = new ApiException($status, (string) $raw, null);
                if ($error->isRetryable() && $attempt < $this->maxRetries) {
                    $lastError = $error;
                    usleep((int) (2 ** $attempt * 250_000));
                    continue;
                }
                throw $error;
            }

            if ($status === 204 || $raw === '') {
                return null;
            }

            $decoded = json_decode((string) $raw, true);

            return json_last_error() === JSON_ERROR_NONE ? $decoded : (string) $raw;
        }

        throw $lastError ?? new ApiException(0, 'Request failed', null);
    }

${spec.operations.map((operation) => methodFor(operation)).join("\n\n")}
}
`;
}

export function generatePhp(spec: SdkSpec): GeneratedSdk {
  const vendor = "OpenApiStudio";
  const ns = `${vendor}\\${toPascal(spec.packageName)}`;
  const first = spec.operations[0];

  const files: GeneratedFile[] = [
    { path: `src/${spec.namespace}Client.php`, contents: clientFile(spec, ns) },
    {
      path: "src/ApiException.php",
      contents: `<?php

declare(strict_types=1);

namespace ${ns};

/** Thrown for any non-2xx response. */
final class ApiException extends \\RuntimeException
{
    public function __construct(
        private int $statusCode,
        private string $body,
        private ?string $requestId,
    ) {
        parent::__construct(sprintf('HTTP %d', $statusCode));
    }

    public function getStatusCode(): int
    {
        return $this->statusCode;
    }

    public function getBody(): string
    {
        return $this->body;
    }

    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /** True when retrying the request could succeed. */
    public function isRetryable(): bool
    {
        return $this->statusCode === 429 || $this->statusCode >= 500;
    }
}
`,
    },
    ...modelFiles(spec, ns),
    {
      path: "composer.json",
      contents: `${JSON.stringify(
        {
          name: `openapi-studio/${spec.packageName}`,
          description: spec.description,
          type: "library",
          license: "MIT",
          require: { php: ">=8.1", "ext-curl": "*", "ext-json": "*" },
          autoload: { "psr-4": { [`${ns.replace(/\\/g, "\\\\")}\\\\`]: "src/" } },
        },
        null,
        2,
      )}\n`,
    },
    {
      path: "README.md",
      contents: `# ${spec.title} — PHP SDK

${spec.description}

Generated by OpenAPI Studio AI from \`${spec.title}\` v${spec.version}. Requires PHP 8.1+.

\`\`\`bash
composer require openapi-studio/${spec.packageName}
\`\`\`

\`\`\`php
<?php

use ${ns}\\${spec.namespace}Client;
use ${ns}\\ApiException;

$client = new ${spec.namespace}Client('${spec.baseUrl}');

try {
    $result = $client->${first ? toCamel(first.methodName) : "call"}(${first?.pathParams.map(() => "'123'").join(", ") ?? ""});
    var_dump($result);
} catch (ApiException $error) {
    fwrite(STDERR, $error->getStatusCode() . ': ' . $error->getBody());
}
\`\`\`
`,
    },
  ];

  return {
    language: "php",
    files,
    entryPoint: `src/${spec.namespace}Client.php`,
    installCommand: `composer require openapi-studio/${spec.packageName}`,
  };
}
