import {
  operationDoc,
  renderPath,
  toSnake,
  type GeneratedFile,
  type GeneratedSdk,
  type SdkOperation,
  type SdkSpec,
  type TypeRef,
} from "./model";

function pyType(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      switch (ref.name) {
        case "integer":
          return "int";
        case "number":
          return "float";
        case "boolean":
          return "bool";
        case "datetime":
          return "datetime";
        case "any":
          return "Any";
        default:
          return "str";
      }
    case "array":
      return `List[${pyType(ref.items)}]`;
    case "map":
      return `Dict[str, ${pyType(ref.values)}]`;
    case "model":
      return `"${ref.name}"`;
    case "enum":
      return "str";
    case "void":
      return "None";
  }
}

function modelsFile(spec: SdkSpec): string {
  const blocks = spec.models.map((model) => {
    if (model.enumValues.length > 0 && model.properties.length === 0) {
      const members = model.enumValues
        .map((value) => `    ${toSnake(value).toUpperCase() || "VALUE"} = ${JSON.stringify(value)}`)
        .join("\n");
      return `class ${model.name}(str, Enum):\n${model.description ? `    """${model.description}"""\n` : ""}${members}\n`;
    }

    // Required fields must precede defaulted fields in a dataclass.
    const ordered = [...model.properties].sort((a, b) => Number(b.required) - Number(a.required));
    const fields = ordered.map((property) => {
      const optional = property.required && !property.nullable;
      const type = optional ? pyType(property.type) : `Optional[${pyType(property.type)}]`;
      const suffix = optional ? "" : " = None";
      const comment = property.description ? `  # ${property.description.split("\n")[0]}` : "";
      return `    ${toSnake(property.name)}: ${type}${suffix}${comment}`;
    });

    const fromDict = ordered
      .map(
        (property) =>
          `            ${toSnake(property.name)}=payload.get(${JSON.stringify(property.wireName)}),`,
      )
      .join("\n");
    const toDict = ordered
      .map(
        (property) =>
          `            ${JSON.stringify(property.wireName)}: self.${toSnake(property.name)},`,
      )
      .join("\n");

    return `@dataclass
class ${model.name}:
    """${model.description ?? model.name}"""

${fields.join("\n") || "    pass"}

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "${model.name}":
        return cls(
${fromDict}
        )

    def to_dict(self) -> Dict[str, Any]:
        return {
${toDict}
        }
`;
  });

  return `"""Models generated by OpenAPI Studio AI from ${spec.title} ${spec.version}."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

__all__ = [${spec.models.map((model) => JSON.stringify(model.name)).join(", ")}]


${blocks.join("\n\n")}
`;
}

function authSetup(spec: SdkSpec): { params: string[]; assigns: string[]; apply: string[] } {
  const params: string[] = [];
  const assigns: string[] = [];
  const apply: string[] = [];

  for (const auth of spec.auth) {
    switch (auth.kind) {
      case "bearer":
      case "oauth2":
        if (!params.includes("access_token: Optional[str] = None")) {
          params.push("access_token: Optional[str] = None");
          assigns.push(
            '        self.access_token = access_token or os.environ.get("API_ACCESS_TOKEN")',
          );
          apply.push(
            "        if self.access_token:",
            '            headers["Authorization"] = f"Bearer {self.access_token}"',
          );
        }
        break;
      case "basic":
        params.push("username: Optional[str] = None", "password: Optional[str] = None");
        assigns.push("        self.username = username", "        self.password = password");
        apply.push(
          "        if self.username is not None:",
          '            raw = f"{self.username}:{self.password or \'\'}".encode("utf-8")',
          '            headers["Authorization"] = "Basic " + base64.b64encode(raw).decode("ascii")',
        );
        break;
      case "apiKeyHeader":
        if (!params.includes("api_key: Optional[str] = None")) {
          params.push("api_key: Optional[str] = None");
          assigns.push('        self.api_key = api_key or os.environ.get("API_KEY")');
        }
        apply.push(
          "        if self.api_key:",
          `            headers[${JSON.stringify(auth.parameterName ?? "X-API-Key")}] = self.api_key`,
        );
        break;
      case "apiKeyQuery":
        if (!params.includes("api_key: Optional[str] = None")) {
          params.push("api_key: Optional[str] = None");
          assigns.push('        self.api_key = api_key or os.environ.get("API_KEY")');
        }
        apply.push(
          "        if self.api_key:",
          `            params[${JSON.stringify(auth.parameterName ?? "api_key")}] = self.api_key`,
        );
        break;
      default:
        break;
    }
  }

  if (apply.length === 0)
    apply.push("        return None  # This API declares no security schemes.");
  return { params, assigns, apply };
}

function methodFor(operation: SdkOperation): string {
  const args = [
    "self",
    ...operation.pathParams.map(
      (parameter) => `${toSnake(parameter.name)}: ${pyType(parameter.type)}`,
    ),
    ...(operation.requestBody
      ? [
          `body: ${operation.requestBody.required ? "Dict[str, Any]" : "Optional[Dict[str, Any]] = None"}`,
        ]
      : []),
    ...operation.queryParams.map(
      (parameter) =>
        `${toSnake(parameter.name)}: ${parameter.required ? pyType(parameter.type) : `Optional[${pyType(parameter.type)}] = None`}`,
    ),
  ];

  const path = renderPath(operation, (parameter) => `{${toSnake(parameter.name)}}`);
  const queryLines = operation.queryParams
    .map(
      (parameter) =>
        `        if ${toSnake(parameter.name)} is not None:\n            params[${JSON.stringify(parameter.wireName)}] = ${toSnake(parameter.name)}`,
    )
    .join("\n");

  const doc = operationDoc(operation)
    .map((line) => `        ${line}`)
    .join("\n");

  return `    def ${toSnake(operation.methodName)}(${args.join(", ")}) -> Any:
        """
${doc}
        """
        params: Dict[str, Any] = {}
${queryLines || "        pass"}
        return self._request(
            ${JSON.stringify(operation.httpMethod)},
            f"${path}",
            params=params,
            json_body=${operation.requestBody ? "body" : "None"},
        )`;
}

function clientFile(spec: SdkSpec): string {
  const auth = authSetup(spec);
  const initParams = [
    "self",
    `base_url: str = ${JSON.stringify(spec.baseUrl)}`,
    ...auth.params,
    "timeout: float = 30.0",
    "max_retries: int = 2",
  ];

  return `"""Client generated by OpenAPI Studio AI from ${spec.title} ${spec.version}."""

from __future__ import annotations

import base64
import os
import time
from typing import Any, Dict, Iterator, Optional

import httpx


class ApiError(Exception):
    """Raised for any non-2xx response."""

    def __init__(self, status_code: int, body: Any, request_id: Optional[str] = None) -> None:
        super().__init__(f"HTTP {status_code}")
        self.status_code = status_code
        self.body = body
        self.request_id = request_id

    @property
    def retryable(self) -> bool:
        return self.status_code == 429 or self.status_code >= 500


class ${spec.namespace}Client:
    """${spec.description}

    Example:
        >>> client = ${spec.namespace}Client()
        >>> # client.${spec.operations[0]?.methodName ?? "call"}(...)
    """

    def __init__(${initParams.join(", ")}) -> None:
        self.base_url = base_url.rstrip("/")
${auth.assigns.join("\n") || "        pass"}
        self.timeout = timeout
        self.max_retries = max_retries
        self._client = httpx.Client(timeout=timeout)

    def __enter__(self) -> "${spec.namespace}Client":
        return self

    def __exit__(self, *_exc: Any) -> None:
        self.close()

    def close(self) -> None:
        self._client.close()

    def _apply_auth(self, headers: Dict[str, str], params: Dict[str, Any]) -> None:
${auth.apply.join("\n")}

    def _request(
        self,
        method: str,
        path: str,
        params: Optional[Dict[str, Any]] = None,
        json_body: Optional[Any] = None,
        headers: Optional[Dict[str, str]] = None,
    ) -> Any:
        request_headers: Dict[str, str] = {"Accept": "application/json"}
        request_headers.update(headers or {})
        query: Dict[str, Any] = dict(params or {})
        self._apply_auth(request_headers, query)

        url = f"{self.base_url}{path}"
        last_error: Optional[Exception] = None

        for attempt in range(self.max_retries + 1):
            try:
                response = self._client.request(
                    method, url, params=query, json=json_body, headers=request_headers
                )
            except httpx.HTTPError as exc:  # network-level failure
                last_error = exc
                if attempt >= self.max_retries:
                    break
                time.sleep(2 ** attempt * 0.25)
                continue

            if response.status_code >= 400:
                payload = self._read(response)
                error = ApiError(response.status_code, payload, response.headers.get("x-request-id"))
                if error.retryable and attempt < self.max_retries:
                    retry_after = response.headers.get("retry-after")
                    time.sleep(float(retry_after) if retry_after else 2 ** attempt * 0.25)
                    last_error = error
                    continue
                raise error

            if response.status_code == 204:
                return None
            return self._read(response)

        raise last_error or RuntimeError("Request failed")

    @staticmethod
    def _read(response: "httpx.Response") -> Any:
        if "json" in response.headers.get("content-type", ""):
            try:
                return response.json()
            except ValueError:
                return None
        return response.text

    def paginate(self, fetch_page: Any, next_cursor: Any = None, max_pages: int = 100) -> Iterator[Any]:
        """Yield successive pages of a paginated endpoint."""
        cursor = None
        for _ in range(max_pages):
            page = fetch_page(cursor)
            yield page
            candidate = next_cursor(page) if next_cursor else _default_next_cursor(page)
            if candidate is None or candidate == cursor:
                return
            cursor = candidate

${spec.operations.map((operation) => methodFor(operation)).join("\n\n")}


def _default_next_cursor(page: Any) -> Optional[Any]:
    if isinstance(page, dict):
        for key in ("nextCursor", "next_cursor", "next", "cursor"):
            if page.get(key) is not None:
                return page[key]
    return None
`;
}

export function generatePython(spec: SdkSpec): GeneratedSdk {
  const moduleName = spec.packageName.replace(/-/g, "_");
  const first = spec.operations[0];

  const files: GeneratedFile[] = [
    {
      path: `${moduleName}/__init__.py`,
      contents: `from .client import ${spec.namespace}Client, ApiError\nfrom .models import *  # noqa: F401,F403\n\n__all__ = ["${spec.namespace}Client", "ApiError"]\n`,
    },
    { path: `${moduleName}/client.py`, contents: clientFile(spec) },
    { path: `${moduleName}/models.py`, contents: modelsFile(spec) },
    {
      path: "pyproject.toml",
      contents: `[project]
name = "${spec.packageName}"
version = "${spec.version}"
description = "${spec.description.replace(/"/g, "'")}"
requires-python = ">=3.9"
dependencies = ["httpx>=0.27"]
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["${moduleName}"]
`,
    },
    {
      path: "README.md",
      contents: `# ${spec.title} — Python SDK

${spec.description}

Generated by OpenAPI Studio AI from \`${spec.title}\` v${spec.version}.

\`\`\`bash
pip install ${spec.packageName}
\`\`\`

\`\`\`python
from ${moduleName} import ${spec.namespace}Client, ApiError

with ${spec.namespace}Client(base_url="${spec.baseUrl}") as client:
    try:
        result = client.${first ? toSnake(first.methodName) : "call"}(${first?.pathParams.map(() => '"123"').join(", ") ?? ""})
        print(result)
    except ApiError as error:
        print(error.status_code, error.body)
\`\`\`

429 and 5xx responses are retried automatically with exponential backoff
(\`max_retries\`, default 2), honouring \`Retry-After\` when present.
`,
    },
  ];

  return {
    language: "python",
    files,
    entryPoint: `${moduleName}/client.py`,
    installCommand: `pip install ${spec.packageName}`,
  };
}
