import {
  operationDoc,
  renderPath,
  type GeneratedFile,
  type GeneratedSdk,
  type SdkOperation,
  type SdkSpec,
  type TypeRef,
} from "./model";

function tsType(ref: TypeRef): string {
  switch (ref.kind) {
    case "primitive":
      switch (ref.name) {
        case "integer":
        case "number":
          return "number";
        case "boolean":
          return "boolean";
        case "datetime":
        case "string":
          return "string";
        default:
          return "unknown";
      }
    case "array":
      return `${tsType(ref.items)}[]`;
    case "map":
      return `Record<string, ${tsType(ref.values)}>`;
    case "model":
      return ref.name;
    case "enum":
      return ref.values.map((value) => JSON.stringify(value)).join(" | ") || "string";
    case "void":
      return "void";
  }
}

function docBlock(lines: readonly string[], indent = ""): string {
  if (lines.length === 0) return "";
  return `${indent}/**\n${lines.map((line) => `${indent} * ${line}`).join("\n")}\n${indent} */\n`;
}

function modelsFile(spec: SdkSpec): string {
  const parts: string[] = [
    `// Generated by OpenAPI Studio AI from ${spec.title} ${spec.version}.`,
    `// Do not edit by hand — regenerate instead.`,
    "",
  ];

  for (const model of spec.models) {
    if (model.enumValues.length > 0 && model.properties.length === 0) {
      parts.push(
        docBlock(model.description ? [model.description] : []),
        `export type ${model.name} = ${model.enumValues.map((value) => JSON.stringify(value)).join(" | ")};`,
        "",
      );
      continue;
    }

    parts.push(docBlock(model.description ? [model.description] : []));
    parts.push(`export interface ${model.name} {`);
    for (const property of model.properties) {
      const doc = [property.description, property.deprecated ? "@deprecated" : null].filter(
        (line): line is string => Boolean(line),
      );
      if (doc.length > 0) parts.push(docBlock(doc, "  ").trimEnd());
      const optional = property.required ? "" : "?";
      const nullable = property.nullable ? " | null" : "";
      parts.push(`  ${property.name}${optional}: ${tsType(property.type)}${nullable};`);
    }
    if (model.additionalProperties) {
      parts.push(`  [key: string]: ${tsType(model.additionalProperties)} | undefined;`);
    }
    parts.push("}", "");
  }

  return `${parts.join("\n")}\n`;
}

function authOptions(spec: SdkSpec): string {
  const fields = new Set<string>();
  for (const auth of spec.auth) {
    switch (auth.kind) {
      case "bearer":
      case "oauth2":
        fields.add(
          "  /** Bearer token sent as `Authorization: Bearer <token>`. */\n  accessToken?: string | (() => string | Promise<string>);",
        );
        break;
      case "basic":
        fields.add("  /** HTTP Basic credentials. */\n  username?: string;\n  password?: string;");
        break;
      case "apiKeyHeader":
      case "apiKeyQuery":
        fields.add("  /** API key credential. */\n  apiKey?: string;");
        break;
      default:
        break;
    }
  }
  return [...fields].join("\n");
}

function authApplication(spec: SdkSpec): string {
  const lines: string[] = [];
  for (const auth of spec.auth) {
    switch (auth.kind) {
      case "bearer":
      case "oauth2":
        lines.push(
          "    if (this.options.accessToken) {",
          "      const token =",
          '        typeof this.options.accessToken === "function"',
          "          ? await this.options.accessToken()",
          "          : this.options.accessToken;",
          '      if (token) headers.set("authorization", `Bearer ${token}`);',
          "    }",
        );
        break;
      case "basic":
        lines.push(
          "    if (this.options.username !== undefined) {",
          '      const raw = `${this.options.username}:${this.options.password ?? ""}`;',
          "      const encoded =",
          '        typeof btoa === "function" ? btoa(raw) : Buffer.from(raw, "utf8").toString("base64");',
          '      headers.set("authorization", `Basic ${encoded}`);',
          "    }",
        );
        break;
      case "apiKeyHeader":
        lines.push(
          `    if (this.options.apiKey) headers.set(${JSON.stringify((auth.parameterName ?? "x-api-key").toLowerCase())}, this.options.apiKey);`,
        );
        break;
      case "apiKeyQuery":
        lines.push(
          `    if (this.options.apiKey) query.set(${JSON.stringify(auth.parameterName ?? "api_key")}, this.options.apiKey);`,
        );
        break;
      default:
        break;
    }
  }
  return lines.join("\n") || "    // This API declares no security schemes.";
}

function methodFor(operation: SdkOperation): string {
  const args: string[] = [];
  for (const parameter of operation.pathParams) {
    args.push(`${parameter.name}: ${tsType(parameter.type)}`);
  }
  if (operation.requestBody) {
    args.push(
      `body${operation.requestBody.required ? "" : "?"}: ${tsType(operation.requestBody.type)}`,
    );
  }

  const optionFields = [
    ...operation.queryParams.map(
      (parameter) => `${parameter.name}${parameter.required ? "" : "?"}: ${tsType(parameter.type)}`,
    ),
    ...operation.headerParams.map(
      (parameter) =>
        `${JSON.stringify(parameter.wireName)}${parameter.required ? "" : "?"}: string`,
    ),
  ];
  const optionsType =
    optionFields.length > 0 ? `{ ${optionFields.join("; ")} } & RequestOptions` : "RequestOptions";
  const optionsRequired = operation.queryParams.some((parameter) => parameter.required);
  args.push(`options${optionsRequired ? "" : "?"}: ${optionsType}`);

  const returnType =
    operation.responseType.kind === "void" ? "void" : tsType(operation.responseType);
  const path = renderPath(
    operation,
    (parameter) => `\${encodeURIComponent(String(${parameter.name}))}`,
  );

  const querySetters = operation.queryParams
    .map(
      (parameter) =>
        `      if (options?.${parameter.name} !== undefined) query.set(${JSON.stringify(parameter.wireName)}, String(options.${parameter.name}));`,
    )
    .join("\n");

  const headerSetters = operation.headerParams
    .map(
      (parameter) =>
        `      if (options?.[${JSON.stringify(parameter.wireName)}] !== undefined) headers[${JSON.stringify(parameter.wireName.toLowerCase())}] = String(options[${JSON.stringify(parameter.wireName)}]);`,
    )
    .join("\n");

  return [
    docBlock(operationDoc(operation), "  ").trimEnd(),
    `  async ${operation.methodName}(${args.join(", ")}): Promise<${returnType}> {`,
    "    const query = new URLSearchParams();",
    querySetters,
    "    const headers: Record<string, string> = {};",
    headerSetters,
    `    return this.request<${returnType}>({`,
    `      method: ${JSON.stringify(operation.httpMethod)},`,
    `      path: \`${path}\`,`,
    "      query,",
    "      headers,",
    operation.requestBody ? "      body," : "      body: undefined,",
    "      signal: options?.signal,",
    "    });",
    "  }",
  ]
    .filter(Boolean)
    .join("\n");
}

function paginationHelper(spec: SdkSpec): string {
  const paginated = spec.operations.filter((operation) => operation.pagination !== "none");
  if (paginated.length === 0) return "";
  return `
  /**
   * Iterate every page of a paginated operation.
   *
   * @example
   * for await (const page of client.paginate((cursor) => client.${paginated[0]?.methodName ?? "list"}({ ${
     paginated[0]?.pagination === "page"
       ? "page: cursor"
       : paginated[0]?.pagination === "offset"
         ? "offset: cursor"
         : "cursor"
   } } as never))) {
   *   console.log(page);
   * }
   */
  async *paginate<T>(
    fetchPage: (cursor: number | string | undefined) => Promise<T>,
    nextCursor: (page: T) => number | string | undefined = defaultNextCursor,
    maxPages = 100,
  ): AsyncGenerator<T, void, undefined> {
    let cursor: number | string | undefined;
    for (let index = 0; index < maxPages; index += 1) {
      const page = await fetchPage(cursor);
      yield page;
      const next = nextCursor(page);
      if (next === undefined || next === null || next === cursor) return;
      cursor = next;
    }
  }
`;
}

function clientFile(spec: SdkSpec): string {
  const modelNames = spec.models.map((model) => model.name);
  const importLine =
    modelNames.length > 0 ? `import type { ${modelNames.join(", ")} } from "./models";\n` : "";

  return `// Generated by OpenAPI Studio AI from ${spec.title} ${spec.version}.
${importLine}
export interface RequestOptions {
  signal?: AbortSignal;
}

export interface ClientOptions {
  /** Override the API base URL. Defaults to ${JSON.stringify(spec.baseUrl)}. */
  baseUrl?: string;
  /** Custom fetch implementation (useful for tests and non-browser runtimes). */
  fetch?: typeof fetch;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
  /** Request timeout in milliseconds. Default: 30000. */
  timeoutMs?: number;
  /** Retry attempts for 429/5xx responses. Default: 2. */
  maxRetries?: number;
${authOptions(spec)}
}

/** Thrown for any non-2xx response. */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly statusText: string,
    readonly body: unknown,
    readonly requestId: string | null,
  ) {
    super(\`\${status} \${statusText}\`);
    this.name = "ApiError";
  }

  /** True when retrying the request could succeed. */
  get retryable(): boolean {
    return this.status === 429 || this.status >= 500;
  }
}

export function defaultNextCursor(page: unknown): number | string | undefined {
  if (page && typeof page === "object") {
    const record = page as Record<string, unknown>;
    const candidate = record.nextCursor ?? record.next_cursor ?? record.next ?? record.cursor;
    if (typeof candidate === "string" || typeof candidate === "number") return candidate;
  }
  return undefined;
}

interface InternalRequest {
  method: string;
  path: string;
  query: URLSearchParams;
  headers: Record<string, string>;
  body: unknown;
  signal?: AbortSignal | undefined;
}

const sleep = (ms: number): Promise<void> => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * ${spec.description}
 *
 * @example
 * const client = new ${spec.namespace}Client({ baseUrl: ${JSON.stringify(spec.baseUrl)} });
 */
export class ${spec.namespace}Client {
  private readonly options: ClientOptions;
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof fetch;

  constructor(options: ClientOptions = {}) {
    this.options = options;
    this.baseUrl = (options.baseUrl ?? ${JSON.stringify(spec.baseUrl)}).replace(/\\/$/, "");
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    if (!this.fetchImpl) {
      throw new Error("No fetch implementation available. Pass one via ClientOptions.fetch.");
    }
  }

  private async applyAuth(headers: Headers, query: URLSearchParams): Promise<void> {
${authApplication(spec)}
  }

  protected async request<T>(init: InternalRequest): Promise<T> {
    const headers = new Headers({ accept: "application/json", ...this.options.headers, ...init.headers });
    const query = new URLSearchParams(init.query);
    await this.applyAuth(headers, query);

    if (init.body !== undefined && !headers.has("content-type")) {
      headers.set("content-type", "application/json");
    }

    const search = query.toString();
    const url = \`\${this.baseUrl}\${init.path}\${search ? \`?\${search}\` : ""}\`;
    const maxRetries = this.options.maxRetries ?? 2;

    let lastError: unknown;
    for (let attempt = 0; attempt <= maxRetries; attempt += 1) {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), this.options.timeoutMs ?? 30_000);
      if (init.signal) init.signal.addEventListener("abort", () => controller.abort(), { once: true });

      try {
        const response = await this.fetchImpl(url, {
          method: init.method,
          headers,
          body: init.body === undefined ? undefined : JSON.stringify(init.body),
          signal: controller.signal,
        });

        if (!response.ok) {
          const payload = await this.readBody(response);
          const error = new ApiError(
            response.status,
            response.statusText,
            payload,
            response.headers.get("x-request-id"),
          );
          if (error.retryable && attempt < maxRetries) {
            const retryAfter = Number(response.headers.get("retry-after"));
            await sleep(Number.isFinite(retryAfter) && retryAfter > 0 ? retryAfter * 1000 : 2 ** attempt * 250);
            lastError = error;
            continue;
          }
          throw error;
        }

        if (response.status === 204) return undefined as T;
        return (await this.readBody(response)) as T;
      } catch (error) {
        if (error instanceof ApiError) throw error;
        lastError = error;
        if (attempt >= maxRetries) break;
        await sleep(2 ** attempt * 250);
      } finally {
        clearTimeout(timeout);
      }
    }
    throw lastError instanceof Error ? lastError : new Error("Request failed");
  }

  private async readBody(response: Response): Promise<unknown> {
    const contentType = response.headers.get("content-type") ?? "";
    if (contentType.includes("json")) {
      try {
        return await response.json();
      } catch {
        return null;
      }
    }
    return await response.text();
  }
${paginationHelper(spec)}
${spec.operations.map((operation) => methodFor(operation)).join("\n\n")}
}

export default ${spec.namespace}Client;
`;
}

function readmeFile(spec: SdkSpec, language: "typescript" | "javascript"): string {
  const first = spec.operations[0];
  const call = first
    ? `await client.${first.methodName}(${[
        ...first.pathParams.map(() => '"123"'),
        ...(first.requestBody ? ["{ /* body */ }"] : []),
      ].join(", ")});`
    : "// No operations documented yet.";

  return `# ${spec.title} — ${language === "typescript" ? "TypeScript" : "JavaScript"} SDK

${spec.description}

Generated by [OpenAPI Studio AI](https://github.com/itsshreyasbhardwaj-design/openapi-studio-ai) from \`${spec.title}\` v${spec.version}.

## Install

\`\`\`bash
npm install ${spec.packageName}
\`\`\`

## Usage

\`\`\`${language === "typescript" ? "ts" : "js"}
import { ${spec.namespace}Client } from "${spec.packageName}";

const client = new ${spec.namespace}Client({
  baseUrl: "${spec.baseUrl}",${spec.auth.some((auth) => auth.kind === "bearer" || auth.kind === "oauth2") ? "\n  accessToken: process.env.API_TOKEN," : ""}${spec.auth.some((auth) => auth.kind.startsWith("apiKey")) ? "\n  apiKey: process.env.API_KEY," : ""}
});

${call}
\`\`\`

## Error handling

\`\`\`${language === "typescript" ? "ts" : "js"}
import { ApiError } from "${spec.packageName}";

try {
  ${call}
} catch (error) {
  if (error instanceof ApiError) {
    console.error(error.status, error.body, error.requestId);
    if (error.retryable) {
      // 429 and 5xx responses are retried automatically (maxRetries option).
    }
  }
}
\`\`\`

## Configuration

| Option | Default | Description |
| --- | --- | --- |
| \`baseUrl\` | \`${spec.baseUrl}\` | API origin. |
| \`timeoutMs\` | \`30000\` | Per-request timeout. |
| \`maxRetries\` | \`2\` | Retries for 429/5xx with exponential backoff. |
| \`fetch\` | \`globalThis.fetch\` | Custom transport for tests. |
`;
}

function packageJson(spec: SdkSpec, language: "typescript" | "javascript"): string {
  return `${JSON.stringify(
    {
      name: spec.packageName,
      version: spec.version,
      description: spec.description,
      type: "module",
      main: language === "typescript" ? "dist/index.js" : "src/index.js",
      types: language === "typescript" ? "dist/index.d.ts" : undefined,
      files: language === "typescript" ? ["dist"] : ["src"],
      scripts: language === "typescript" ? { build: "tsc -p tsconfig.json" } : {},
      license: "MIT",
    },
    null,
    2,
  )}\n`;
}

export function generateTypeScript(spec: SdkSpec): GeneratedSdk {
  const files: GeneratedFile[] = [
    { path: "src/models.ts", contents: modelsFile(spec) },
    { path: "src/client.ts", contents: clientFile(spec) },
    {
      path: "src/index.ts",
      contents: `export * from "./client";\nexport * from "./models";\n`,
    },
    { path: "package.json", contents: packageJson(spec, "typescript") },
    {
      path: "tsconfig.json",
      contents: `${JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "bundler",
            declaration: true,
            strict: true,
            outDir: "dist",
            lib: ["ES2022", "DOM"],
          },
          include: ["src"],
        },
        null,
        2,
      )}\n`,
    },
    { path: "README.md", contents: readmeFile(spec, "typescript") },
  ];

  return {
    language: "typescript",
    files,
    entryPoint: "src/client.ts",
    installCommand: `npm install ${spec.packageName}`,
  };
}

export { tsType, docBlock, readmeFile, packageJson, authOptions, authApplication };
